# .github/workflows/hello-world.yml
name: Hello World Action

# Trigger the workflow manually via GitHub's workflow_dispatch event
on:
  workflow_dispatch:

# Define the jobs that will run
jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so the workflow can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      # Run a "Hello, World!" script
      - name: Say Hello
        run: echo "Hello, World!"

      - name: Run a runbook in Octopus Deploy 🐙
        uses: OctopusDeploy/run-runbook-action@v3
        env:
          OCTOPUS_API_KEY: ${{ secrets.API_KEY  }}
          OCTOPUS_URL: ${{ secrets.SERVER }}
          OCTOPUS_SPACE: 'Caitlyn'
        with:
          project: 'gh_action_test'
          runbook: 'gh_action_test'
          environments: |
            'Development'
