# .github/workflows/hello-octopus-deploy.yml
name: Hello Octopus Deploy API Key

on:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    env:
      OCTOPUS_SPACE: 'Caitlyn'
      OCTOPUS_API_KEY: ${{ secrets.API_KEY  }}
      OCTOPUS_URL: ${{ secrets.SERVER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Your own build steps go here!
      - name: Your build ✨
        run: echo "Your build steps!"
      
      # Action to Create a Release
      - name: Create a release in Octopus Deploy 🐙
        uses: OctopusDeploy/create-release-action@v3
        with:
          project: 'gh_action_test'
          release_number: '2.0.0'
          git_ref: ${{ github.ref }}
          git_commit: ${{ github.sha }}
      
      # Action to Deploy a Release
      - name: Deploy a release in Octopus Deploy 🐙
        uses: OctopusDeploy/deploy-release-action@v3
        with:
          project: 'gh_action_test'
          release_number: '2.0.0'
          environments: |
            Development
          variables: |
            Foo: Bar
            Fizz: Buzz
          git_ref: ${{ github.ref }}
          git_commit: ${{ github.sha }}
