# .github/workflows/hello-octopus-deploy.yml
name: Hello Octopus Deploy

on:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    env:
      OCTOPUS_SPACE: 'Outer Space'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Your own build steps go here!
      - name: Your build ✨
        run: echo "Your build steps!"

      # Action to Login to Octopus Deploy
      - name: Login to Octopus Deploy 🐙
        uses: OctopusDeploy/login@v1
        with: 
          server: https://team-github.testoctopus.app
          service_account_id: a1af8709-bb78-414b-9c81-4cb845eeb2e2
      
      # Action to Create a Release
      - name: Create a release in Octopus Deploy 🐙
        uses: OctopusDeploy/create-release-action@v3
        with:
          project: 'MyProject'
          release_number: '1.0.0'
          git_ref: ${{ github.ref }}
          git_commit: ${{ github.sha }}
      
      # Action to Deploy a Release
      - name: Deploy a release in Octopus Deploy 🐙
        uses: OctopusDeploy/deploy-release-action@v3
        with:
          project: 'MyProject'
          release_number: '1.0.0'
          environments: |
            Development
          variables: |
            Foo: Bar
            Fizz: Buzz
          git_ref: ${{ github.ref }}
          git_commit: ${{ github.sha }}
