# .github/workflows/hello-world-oicd.yml
name: Hello OICD Action

# Trigger the workflow manually via GitHub's workflow_dispatch event
on:
  workflow_dispatch:

# Define the jobs that will run
jobs:
  say_hello:
    runs-on: ubuntu-latest

    permissions:
      # Add any additional permissions your job requires here
      id-token: write # This is required to obtain the ID token from GitHub Actions

    env:
      OCTOPUS_SPACE: 'Caitlyn'

    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so the workflow can access it
      - name: Checkout repository
        uses: actions/checkout@v3 # dont need this step if you're just running a runbook - do need for release

      - name: Your build
        run: echo "Your build steps go here!"

      - name: Login to Octopus Deploy 
        uses: OctopusDeploy/login@v1
        with: 
          server: https://team-github.testoctopus.app
          service_account_id: a1af8709-bb78-414b-9c81-4cb845eeb2e2

      # - name: Run a runbook in Octopus Deploy 🐙
      #   uses: OctopusDeploy/run-runbook-action@v3
      #   env:
      #     OCTOPUS_SPACE: 'Caitlyn'
      #   with:
      #     project: 'gh_action_test'
      #     runbook: 'gh_action_test'
      #     environments: |
      #       Development
      
      - name: Create a release in Octopus Deploy 🐙
        uses: OctopusDeploy/create-release-action@v3
        with:
          project: 'db_action_test'
          release_number: '1.0.0'
      
      - name: Deploy a release in Octopus Deploy 🐙
        uses: OctopusDeploy/deploy-release-action@v3
        with:
          project: 'db_action_test'
          release_number: '1.0.0'
          environments: |
            Development
          variables: |
            Foo: Bar
            Fizz: Buzz
